mongo:
  container_name: mongo
  build: ./mongo
  hostname: mongo
  domainname: docker
  volumes:
    - ./app/data/db:/data/db
  ports:
    - "27017:27017"
    - "6379:6379"
  expose:
    - "27017"
    - "6379"
  environment:
    - DEBUG=true
learninglocker:
  container_name: learninglocker
  build: ./locker
  ports:
    - "3000:3000"
    - "3001:3001"
  expose:
    - "3000"
    - "3001"
  hostname: learninglocker
  domainname: docker
  environment:
    - VIRTUAL_HOST=learninglocker.docker
    - DEBUG=true
  volumes:
    - ./app/logs:/var/log/nginx
  links:
    - mongo
