mailhog:
  container_name: mailhog
  hostname: mailhog
  domainname: docker
  image: diyan/mailhog
  ports:
    - "1025:1025"
    - "8025:8025"
mongo:
  container_name: mongo
  build: ./mongo
  hostname: mongo
  domainname: docker
  volumes:
    - ./app/data/db:/data/db
  ports:
    - "27017:27017"
  environment:
    - DEBUG=true
learninglocker:
  container_name: learninglocker
  build: ./locker
  ports:
    - "8080:80"
  expose:
    - "8080"
  hostname: learninglocker
  domainname: docker
  environment:
    - VIRTUAL_HOST=learninglocker.docker
    - DEBUG=true
  volumes:
    - ./app/logs:/var/log/httpd
  links:
    - mongo
    - mailhog
